#############################################################################
# Makefile for building: nim.app/Contents/MacOS/nim
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun Apr 14 23:57:41 2013
# Project:  nim.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-llvm -o Makefile nim.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W -std=c++11 -stdlib=libc++ $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-llvm -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -ISrc -I. -I. -F/Library/Frameworks
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -stdlib=libc++
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Src/EnvVarEditor.cpp \
		Src/Main.cpp \
		Src/NIM.cpp \
		Src/NodeInstance.cpp \
		Src/NodeInstanceManager.cpp \
		Src/NodeInstanceSettings.cpp \
		Src/NodeInstanceWidget.cpp \
		Src/NoticeMessageBox.cpp \
		Src/Precompiled.cpp \
		Src/QTUtils.cpp moc_EnvVarEditor.cpp \
		moc_NIM.cpp \
		moc_NodeInstance.cpp \
		moc_NodeInstanceWidget.cpp \
		moc_NoticeMessageBox.cpp \
		moc_QTUtils.cpp \
		qrc_nim.cpp
OBJECTS       = EnvVarEditor.o \
		Main.o \
		NIM.o \
		NodeInstance.o \
		NodeInstanceManager.o \
		NodeInstanceSettings.o \
		NodeInstanceWidget.o \
		NoticeMessageBox.o \
		Precompiled.o \
		QTUtils.o \
		moc_EnvVarEditor.o \
		moc_NIM.o \
		moc_NodeInstance.o \
		moc_NodeInstanceWidget.o \
		moc_NoticeMessageBox.o \
		moc_QTUtils.o \
		qrc_nim.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/llvm.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		nim.pro
QMAKE_TARGET  = nim
DESTDIR       = 
TARGET        = nim.app/Contents/MacOS/nim

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile nim.app/Contents/PkgInfo nim.app/Contents/Resources/empty.lproj nim.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_NIM.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) nim.app/Contents/MacOS/ || $(MKDIR) nim.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nim.pro  /usr/local/Qt4.8/mkspecs/macx-llvm/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/llvm.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-llvm -o Makefile nim.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/llvm.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-llvm -o Makefile nim.pro

nim.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) nim.app/Contents || $(MKDIR) nim.app/Contents 
	@$(DEL_FILE) nim.app/Contents/PkgInfo
	@echo "APPL????" >nim.app/Contents/PkgInfo
nim.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) nim.app/Contents/Resources || $(MKDIR) nim.app/Contents/Resources 
	@touch nim.app/Contents/Resources/empty.lproj
	
nim.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) nim.app/Contents || $(MKDIR) nim.app/Contents 
	@$(DEL_FILE) nim.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,nim,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.8/mkspecs/macx-llvm/Info.plist.app >nim.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/nim1.0.0 || $(MKDIR) .tmp/nim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nim1.0.0/ && $(COPY_FILE) --parents resource.h Src/EnvVarEditor.h Src/NIM.h Src/NodeInstance.h Src/NodeInstanceManager.h Src/NodeInstanceSettings.h Src/NodeInstanceWidget.h Src/NoticeMessageBox.h Src/Precompiled.h Src/QTUtils.h .tmp/nim1.0.0/ && $(COPY_FILE) --parents nim.qrc .tmp/nim1.0.0/ && $(COPY_FILE) --parents Src/EnvVarEditor.cpp Src/Main.cpp Src/NIM.cpp Src/NodeInstance.cpp Src/NodeInstanceManager.cpp Src/NodeInstanceSettings.cpp Src/NodeInstanceWidget.cpp Src/NoticeMessageBox.cpp Src/Precompiled.cpp Src/QTUtils.cpp .tmp/nim1.0.0/ && $(COPY_FILE) --parents UI/NIM.ui .tmp/nim1.0.0/ && (cd `dirname .tmp/nim1.0.0` && $(TAR) nim1.0.0.tar nim1.0.0 && $(COMPRESS) nim1.0.0.tar) && $(MOVE) `dirname .tmp/nim1.0.0`/nim1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r nim.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_EnvVarEditor.cpp moc_NIM.cpp moc_NodeInstance.cpp moc_NodeInstanceWidget.cpp moc_NoticeMessageBox.cpp moc_QTUtils.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_EnvVarEditor.cpp moc_NIM.cpp moc_NodeInstance.cpp moc_NodeInstanceWidget.cpp moc_NoticeMessageBox.cpp moc_QTUtils.cpp
moc_EnvVarEditor.cpp: Src/NodeInstance.h \
		Src/EnvVarEditor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/EnvVarEditor.h -o moc_EnvVarEditor.cpp

moc_NIM.cpp: Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		ui_NIM.h \
		Src/NIM.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NIM.h -o moc_NIM.cpp

moc_NodeInstance.cpp: Src/NodeInstance.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NodeInstance.h -o moc_NodeInstance.cpp

moc_NodeInstanceWidget.cpp: Src/NodeInstance.h \
		Src/NodeInstanceWidget.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NodeInstanceWidget.h -o moc_NodeInstanceWidget.cpp

moc_NoticeMessageBox.cpp: Src/NoticeMessageBox.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NoticeMessageBox.h -o moc_NoticeMessageBox.cpp

moc_QTUtils.cpp: Src/QTUtils.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/QTUtils.h -o moc_QTUtils.cpp

compiler_rcc_make_all: qrc_nim.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_nim.cpp
qrc_nim.cpp: nim.qrc \
		Resources/shutdown-icon.png \
		Resources/stop-node.png \
		Resources/theme.css \
		Resources/configuration-icon.png \
		Resources/delete-node.png \
		Resources/add-node.png \
		Resources/checkbox.png \
		Resources/down_arrow.png \
		Resources/main-icon.png \
		Resources/start-node.png \
		Resources/more-options.png \
		Resources/handle.png
	/Developer/Tools/Qt/rcc -name nim nim.qrc -o qrc_nim.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_NIM.h
compiler_uic_clean:
	-$(DEL_FILE) ui_NIM.h
ui_NIM.h: UI/NIM.ui
	/Developer/Tools/Qt/uic UI/NIM.ui -o ui_NIM.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

EnvVarEditor.o: Src/EnvVarEditor.cpp Src/Precompiled.h \
		Src/EnvVarEditor.h \
		Src/NodeInstance.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvVarEditor.o Src/EnvVarEditor.cpp

Main.o: Src/Main.cpp Src/Precompiled.h \
		Src/NIM.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		ui_NIM.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Src/Main.cpp

NIM.o: Src/NIM.cpp Src/Precompiled.h \
		Src/NIM.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		ui_NIM.h \
		Src/NodeInstanceWidget.h \
		Src/NoticeMessageBox.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NIM.o Src/NIM.cpp

NodeInstance.o: Src/NodeInstance.cpp Src/Precompiled.h \
		Src/NodeInstance.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NodeInstance.o Src/NodeInstance.cpp

NodeInstanceManager.o: Src/NodeInstanceManager.cpp Src/Precompiled.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NodeInstanceManager.o Src/NodeInstanceManager.cpp

NodeInstanceSettings.o: Src/NodeInstanceSettings.cpp Src/Precompiled.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NodeInstanceSettings.o Src/NodeInstanceSettings.cpp

NodeInstanceWidget.o: Src/NodeInstanceWidget.cpp Src/Precompiled.h \
		Src/NodeInstanceWidget.h \
		Src/NodeInstance.h \
		Src/QTUtils.h \
		Src/EnvVarEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NodeInstanceWidget.o Src/NodeInstanceWidget.cpp

NoticeMessageBox.o: Src/NoticeMessageBox.cpp Src/Precompiled.h \
		Src/NoticeMessageBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NoticeMessageBox.o Src/NoticeMessageBox.cpp

Precompiled.o: Src/Precompiled.cpp Src/Precompiled.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Precompiled.o Src/Precompiled.cpp

QTUtils.o: Src/QTUtils.cpp Src/Precompiled.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QTUtils.o Src/QTUtils.cpp

moc_EnvVarEditor.o: moc_EnvVarEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EnvVarEditor.o moc_EnvVarEditor.cpp

moc_NIM.o: moc_NIM.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NIM.o moc_NIM.cpp

moc_NodeInstance.o: moc_NodeInstance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NodeInstance.o moc_NodeInstance.cpp

moc_NodeInstanceWidget.o: moc_NodeInstanceWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NodeInstanceWidget.o moc_NodeInstanceWidget.cpp

moc_NoticeMessageBox.o: moc_NoticeMessageBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NoticeMessageBox.o moc_NoticeMessageBox.cpp

moc_QTUtils.o: moc_QTUtils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QTUtils.o moc_QTUtils.cpp

qrc_nim.o: qrc_nim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_nim.o qrc_nim.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

