#############################################################################
# Makefile for building: build.output/nim.app/Contents/MacOS/nim
# Generated by qmake (2.01a) (Qt 4.8.5) on: Tue Apr 16 23:23:38 2013
# Project:  nim.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.5/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang -o Makefile nim.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -stdlib=libc++ -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang -I. -I/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.8.5/include/QtCore -I/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.8.5/include/QtGui -I/usr/local/Trolltech/Qt-4.8.5/include -I. -ISrc -Ibuild.output/.moc -Ibuild.output/.ui -F/usr/local/Trolltech/Qt-4.8.5/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Trolltech/Qt-4.8.5/lib -L/usr/local/Trolltech/Qt-4.8.5/lib -framework QtGui -L/usr/local/Trolltech/Qt-4.8.5/lib -F/usr/local/Trolltech/Qt-4.8.5/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Trolltech/Qt-4.8.5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = build.output/.obj/

####### Files

SOURCES       = Src/EnvVarEditor.cpp \
		Src/Main.cpp \
		Src/NIM.cpp \
		Src/NodeInstance.cpp \
		Src/NodeInstanceManager.cpp \
		Src/NodeInstanceSettings.cpp \
		Src/NodeInstanceWidget.cpp \
		Src/NodeLogWindow.cpp \
		Src/NoticeMessageBox.cpp \
		Src/Precompiled.cpp \
		Src/QTUtils.cpp build.output/.moc/moc_EnvVarEditor.cpp \
		build.output/.moc/moc_NIM.cpp \
		build.output/.moc/moc_NodeInstance.cpp \
		build.output/.moc/moc_NodeInstanceWidget.cpp \
		build.output/.moc/moc_NodeLogWindow.cpp \
		build.output/.moc/moc_NoticeMessageBox.cpp \
		build.output/.moc/moc_QTUtils.cpp \
		build.output/.rcc/qrc_nim.cpp
OBJECTS       = build.output/.obj/EnvVarEditor.o \
		build.output/.obj/Main.o \
		build.output/.obj/NIM.o \
		build.output/.obj/NodeInstance.o \
		build.output/.obj/NodeInstanceManager.o \
		build.output/.obj/NodeInstanceSettings.o \
		build.output/.obj/NodeInstanceWidget.o \
		build.output/.obj/NodeLogWindow.o \
		build.output/.obj/NoticeMessageBox.o \
		build.output/.obj/Precompiled.o \
		build.output/.obj/QTUtils.o \
		build.output/.obj/moc_EnvVarEditor.o \
		build.output/.obj/moc_NIM.o \
		build.output/.obj/moc_NodeInstance.o \
		build.output/.obj/moc_NodeInstanceWidget.o \
		build.output/.obj/moc_NodeLogWindow.o \
		build.output/.obj/moc_NoticeMessageBox.o \
		build.output/.obj/moc_QTUtils.o \
		build.output/.obj/qrc_nim.o
DIST          = /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/clang.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		nim.pro
QMAKE_TARGET  = nim
DESTDIR       = build.output/
TARGET        = build.output/nim.app/Contents/MacOS/nim

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build.output/nim.app/Contents/PkgInfo build.output/nim.app/Contents/Resources/empty.lproj build.output/nim.app/Contents/Info.plist $(TARGET)

$(TARGET): build.output/.ui/ui_NIM.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build.output/nim.app/Contents/MacOS/ || $(MKDIR) build.output/nim.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nim.pro  /usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/clang.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang -o Makefile nim.pro
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/clang.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86_64.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang -o Makefile nim.pro

build.output/nim.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) build.output/nim.app/Contents || $(MKDIR) build.output/nim.app/Contents 
	@$(DEL_FILE) build.output/nim.app/Contents/PkgInfo
	@echo "APPL????" >build.output/nim.app/Contents/PkgInfo
build.output/nim.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) build.output/nim.app/Contents/Resources || $(MKDIR) build.output/nim.app/Contents/Resources 
	@touch build.output/nim.app/Contents/Resources/empty.lproj
	
build.output/nim.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) build.output/nim.app/Contents || $(MKDIR) build.output/nim.app/Contents 
	@$(DEL_FILE) build.output/nim.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,nim,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.8.5/mkspecs/unsupported/macx-clang/Info.plist.app >build.output/nim.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) build.output/.obj/nim1.0.0 || $(MKDIR) build.output/.obj/nim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build.output/.obj/nim1.0.0/ && $(COPY_FILE) --parents resource.h Src/EnvVarEditor.h Src/NIM.h Src/NodeInstance.h Src/NodeInstanceManager.h Src/NodeInstanceSettings.h Src/NodeInstanceWidget.h Src/NodeLogWindow.h Src/NoticeMessageBox.h Src/Precompiled.h Src/QTUtils.h build.output/.obj/nim1.0.0/ && $(COPY_FILE) --parents nim.qrc build.output/.obj/nim1.0.0/ && $(COPY_FILE) --parents Src/EnvVarEditor.cpp Src/Main.cpp Src/NIM.cpp Src/NodeInstance.cpp Src/NodeInstanceManager.cpp Src/NodeInstanceSettings.cpp Src/NodeInstanceWidget.cpp Src/NodeLogWindow.cpp Src/NoticeMessageBox.cpp Src/Precompiled.cpp Src/QTUtils.cpp build.output/.obj/nim1.0.0/ && $(COPY_FILE) --parents UI/NIM.ui build.output/.obj/nim1.0.0/ && (cd `dirname build.output/.obj/nim1.0.0` && $(TAR) nim1.0.0.tar nim1.0.0 && $(COMPRESS) nim1.0.0.tar) && $(MOVE) `dirname build.output/.obj/nim1.0.0`/nim1.0.0.tar.gz . && $(DEL_FILE) -r build.output/.obj/nim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r build.output/nim.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: build.output/.moc/moc_EnvVarEditor.cpp build.output/.moc/moc_NIM.cpp build.output/.moc/moc_NodeInstance.cpp build.output/.moc/moc_NodeInstanceWidget.cpp build.output/.moc/moc_NodeLogWindow.cpp build.output/.moc/moc_NoticeMessageBox.cpp build.output/.moc/moc_QTUtils.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build.output/.moc/moc_EnvVarEditor.cpp build.output/.moc/moc_NIM.cpp build.output/.moc/moc_NodeInstance.cpp build.output/.moc/moc_NodeInstanceWidget.cpp build.output/.moc/moc_NodeLogWindow.cpp build.output/.moc/moc_NoticeMessageBox.cpp build.output/.moc/moc_QTUtils.cpp
build.output/.moc/moc_EnvVarEditor.cpp: Src/NodeInstance.h \
		Src/EnvVarEditor.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/EnvVarEditor.h -o build.output/.moc/moc_EnvVarEditor.cpp

build.output/.moc/moc_NIM.cpp: Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		build.output/.ui/ui_NIM.h \
		Src/NIM.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NIM.h -o build.output/.moc/moc_NIM.cpp

build.output/.moc/moc_NodeInstance.cpp: Src/NodeInstance.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NodeInstance.h -o build.output/.moc/moc_NodeInstance.cpp

build.output/.moc/moc_NodeInstanceWidget.cpp: Src/NodeInstance.h \
		Src/NodeInstanceWidget.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NodeInstanceWidget.h -o build.output/.moc/moc_NodeInstanceWidget.cpp

build.output/.moc/moc_NodeLogWindow.cpp: Src/NodeInstance.h \
		Src/NodeLogWindow.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NodeLogWindow.h -o build.output/.moc/moc_NodeLogWindow.cpp

build.output/.moc/moc_NoticeMessageBox.cpp: Src/NoticeMessageBox.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/NoticeMessageBox.h -o build.output/.moc/moc_NoticeMessageBox.cpp

build.output/.moc/moc_QTUtils.cpp: Src/QTUtils.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Src/QTUtils.h -o build.output/.moc/moc_QTUtils.cpp

compiler_rcc_make_all: build.output/.rcc/qrc_nim.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build.output/.rcc/qrc_nim.cpp
build.output/.rcc/qrc_nim.cpp: nim.qrc \
		Resources/shutdown-icon.png \
		Resources/stop-node.png \
		Resources/theme.css \
		Resources/configuration-icon.png \
		Resources/delete-node.png \
		Resources/add-node.png \
		Resources/checkbox.png \
		Resources/down_arrow.png \
		Resources/main-icon.png \
		Resources/start-node.png \
		Resources/more-options.png \
		Resources/handle.png
	/usr/local/Trolltech/Qt-4.8.5/bin/rcc -name nim nim.qrc -o build.output/.rcc/qrc_nim.cpp

compiler_image_collection_make_all: build.output/.ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build.output/.ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: build.output/.ui/ui_NIM.h
compiler_uic_clean:
	-$(DEL_FILE) build.output/.ui/ui_NIM.h
build.output/.ui/ui_NIM.h: UI/NIM.ui
	/usr/local/Trolltech/Qt-4.8.5/bin/uic UI/NIM.ui -o build.output/.ui/ui_NIM.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build.output/.obj/EnvVarEditor.o: Src/EnvVarEditor.cpp Src/Precompiled.h \
		Src/EnvVarEditor.h \
		Src/NodeInstance.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/EnvVarEditor.o Src/EnvVarEditor.cpp

build.output/.obj/Main.o: Src/Main.cpp Src/Precompiled.h \
		Src/NIM.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		build.output/.ui/ui_NIM.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/Main.o Src/Main.cpp

build.output/.obj/NIM.o: Src/NIM.cpp Src/Precompiled.h \
		Src/NIM.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		build.output/.ui/ui_NIM.h \
		Src/NodeInstanceWidget.h \
		Src/NoticeMessageBox.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NIM.o Src/NIM.cpp

build.output/.obj/NodeInstance.o: Src/NodeInstance.cpp Src/Precompiled.h \
		Src/NodeInstance.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NodeInstance.o Src/NodeInstance.cpp

build.output/.obj/NodeInstanceManager.o: Src/NodeInstanceManager.cpp Src/Precompiled.h \
		Src/NodeInstanceManager.h \
		Src/NodeInstance.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NodeInstanceManager.o Src/NodeInstanceManager.cpp

build.output/.obj/NodeInstanceSettings.o: Src/NodeInstanceSettings.cpp Src/Precompiled.h \
		Src/NodeInstanceSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NodeInstanceSettings.o Src/NodeInstanceSettings.cpp

build.output/.obj/NodeInstanceWidget.o: Src/NodeInstanceWidget.cpp Src/Precompiled.h \
		Src/NodeInstanceWidget.h \
		Src/NodeInstance.h \
		Src/QTUtils.h \
		Src/EnvVarEditor.h \
		Src/NoticeMessageBox.h \
		Src/NodeLogWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NodeInstanceWidget.o Src/NodeInstanceWidget.cpp

build.output/.obj/NodeLogWindow.o: Src/NodeLogWindow.cpp Src/Precompiled.h \
		Src/NodeLogWindow.h \
		Src/NodeInstance.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NodeLogWindow.o Src/NodeLogWindow.cpp

build.output/.obj/NoticeMessageBox.o: Src/NoticeMessageBox.cpp Src/Precompiled.h \
		Src/NoticeMessageBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/NoticeMessageBox.o Src/NoticeMessageBox.cpp

build.output/.obj/Precompiled.o: Src/Precompiled.cpp Src/Precompiled.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/Precompiled.o Src/Precompiled.cpp

build.output/.obj/QTUtils.o: Src/QTUtils.cpp Src/Precompiled.h \
		Src/QTUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/QTUtils.o Src/QTUtils.cpp

build.output/.obj/moc_EnvVarEditor.o: build.output/.moc/moc_EnvVarEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_EnvVarEditor.o build.output/.moc/moc_EnvVarEditor.cpp

build.output/.obj/moc_NIM.o: build.output/.moc/moc_NIM.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_NIM.o build.output/.moc/moc_NIM.cpp

build.output/.obj/moc_NodeInstance.o: build.output/.moc/moc_NodeInstance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_NodeInstance.o build.output/.moc/moc_NodeInstance.cpp

build.output/.obj/moc_NodeInstanceWidget.o: build.output/.moc/moc_NodeInstanceWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_NodeInstanceWidget.o build.output/.moc/moc_NodeInstanceWidget.cpp

build.output/.obj/moc_NodeLogWindow.o: build.output/.moc/moc_NodeLogWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_NodeLogWindow.o build.output/.moc/moc_NodeLogWindow.cpp

build.output/.obj/moc_NoticeMessageBox.o: build.output/.moc/moc_NoticeMessageBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_NoticeMessageBox.o build.output/.moc/moc_NoticeMessageBox.cpp

build.output/.obj/moc_QTUtils.o: build.output/.moc/moc_QTUtils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/moc_QTUtils.o build.output/.moc/moc_QTUtils.cpp

build.output/.obj/qrc_nim.o: build.output/.rcc/qrc_nim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.output/.obj/qrc_nim.o build.output/.rcc/qrc_nim.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

